name: IPTV-Go

on:
  push:
    branches: ["main"]
    paths:
      - '**.go'    
  pull_request:
    branches: ["main"]
    paths:
      - '**.go'

jobs:
  linux_armv6l_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cross Compile for Raspberry Pi
        run: |
          cd ./Golang
          GOOS=linux GOARCH=arm GOARM=6 go build -o allinone_linux_armv6l
      - name: Upload Cross Compile Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: allinone_linux_armv6l
          path: Golang/allinone_linux_armv6l
